### ISSUE TITLE
AbstractChromosome.isValid() is not thread-safe

### ISSUE THREAD

**Issue by cowwoc** [jenetics/jenetics#19]
The Javadoc says that Chromosome implementation must be immutable. `AbstractChromosome` is immutable but not thread-safe, because `_valid` may be set by multiple threads in parallel. Is this safe?

**Comment by cowwoc** [comment]
It also occurs to me that `_genes` should probably be `final`.

**Comment by jenetics** [comment]
You are right, the `isValid` method is not thread-safe. But for two reasons this doesn't matter:
1.) The `isValid` method is always called by one thread by the `Engine`.
2.) Since the genes itself and the sequence of genes are immutable, calls to the `isValid` method are idempotent. Calling the method would always deliver the same result. In the worst case the is-valid state is calculated twice. The `hashCode` method of the Java `String` class uses the same "synchronization" method.

The reason for the non-final `_genes` field is, that I implemented the Java serialization methods (`writeObject`, `readObject`) in the numeric chromosome implementations; for smaller serialzed objects. In this methods I have to set the `_genes` field explicitely.
