### ISSUE TITLE
Batched fitness evaluation

### ISSUE THREAD

**Issue by akousari** [jenetics/jenetics#211]
I was wondering if it's possible to support fitness function batch evaluation in case we want to evaluate many fitness function using the same execution thread. This could be done for one population at a time.

For instance, if you have large volumes of data it would be terribly inefficient to iterate over the data and evaluate fitness functions many times. A solution would be to bundle many fitness functions and feed the data only once. 

I was looking at the code and I have some ideas how this could be done. But I'm affraid it would break the current construct were each Phenotype is a Runnable that is submitted to an executor which in turn calls the respective fitness function (i.e. with the apply method). Any ideas? Does it even make sense to have such a construct?

**Comment by jenetics** [comment]
Jenetics already evaluates the fitness function for the `Phenotype`s in batches. The responsible classes are [org.jenetics.internal.util.RunnableAction](https://github.com/jenetics/jenetics/blob/master/org.jenetics/src/main/java/org/jenetics/internal/util/RunnablesAction.java) for the `ForkJoinPool` and [org.jenetics.internal.util.RunnablesRunnable](https://github.com/jenetics/jenetics/blob/master/org.jenetics/src/main/java/org/jenetics/internal/util/RunnablesRunnable.java) for *normal* `ExecutorService` classes. The batch size is automatically adapted and depends on the number of available cores.

"Terrible inefficient": this sounds really awful ;-) Do you have some numbers? How many data points do you have to process? Whats the population size? Whats the evaluation time of the fitness function?

As a *general purpose* GA implementation, I tried to evaluate the Population as fast as possible. In #197 I tried to improve the CPU utilization for long running fitness functions. You might also want to have a look at the changes for this ticket.

If I understood you correctly, you want to iterate over your data point and calculate *partial* fitness values for each of the phenotype. So you have to load your data only once, right? I currently don't see a way to do this, since it would break the current object encapsulation.

**Comment by akousari** [comment]
Yes that's what I saw in the code as well but to scale more efficiently I need to provide more work to different cores. So worst case there are 20 million data points. With proper caching I can run the fitness function in 10 or 15 seconds. The computation itself is not heavy but what makes the fitness function slow is the volume of data I'm processing. Also bundling fitness functions together brings little overhead as a whole (I found that 10 to 20 is a good number in order to benefit from multicores as well).

So instead of having a for loop that goes over each Phenotype (i.e. Runnable) =>RunnablesRunnable . Ideally I would get a List<Pehenotype> that would be ran by one thread instead of many threads thus bundling many fitness functions in one go. 

Ya I can see that it's not trivial to make this change I started looking but quickly gave up since I couldn't see where I can fit this without bringing additional constructs. I might continue digging if I have some time.
