### ISSUE TITLE
Improve the package  structure

### ISSUE THREAD

**Issue by ZiyeHan** [jenetics/jenetics#224]
Gene classes, Chromosome classes, and Selector classes are all under the same package. I think to help developers better understand and browse the project, we should put them in different packages divided by real-life meaning. For example, make a package called "selector", and put those selector classes into it.

**Comment by jenetics** [comment]
When I started the library I also thought about this kind of package structure. But if I go down this road, I would also have to create an `alterer`, `chromosome` or `gene` package. Which would lead to the following package structure.

├── org.jenetics
├── org.jenetics.alterer
├── org.jenetics.chromosome
├── org.jenetics.engine
├── org.jenetics.gene
├── org.jenetics.selector
├── org.jenetics.stat
└── org.jenetics.util

Now I have the problem, that the base (domain) classes are moved one package up in the package hierarchy. The `engine` package is on the same level as the `selector` package. Which doesn't reflect the intended (and implemented) architecture. The base classes (selectors, alterers, ...) doesn't use any functionality of the `engine` package. 

The base package currently consists of 50 public classes and interfaces. Since this is not the smallest number, it is also not very likely that this number will increase substantially. I've already started to put additional genes, chromosomes, selectors and alterers into a separate module (`org.jenetics`), which is currently in an incubation state; you have to compile itself, because it's not published to maven.

This are roughly the reasons for the current package structure. Do you have other arguments or thoughts, way a changed package structure makes it easier to use the library? Maybe you can convince me :-)

**Comment by ZiyeHan** [comment]
Your words make sense, but I still can't accept the current structure... When your IDE order those classes in an alphabetical order, it looks very annoying. I was trying to make a UML Class Diagram for your project, and the result is just like spaghetti. You are the main developer so you are already familiar with everything, but for new contributors, trust me, it is annoying.

I suggest you can put them this way:
├── org.jenetics.domain
├── org.jenetics.domain.gene
├── org.jenetics.domain.chromosome
├── org.jenetics.operator.alterer
├── org.jenetics.operator.selector
├── org.jenetics.engine
├── org.jenetics.stat
└── org.jenetics.util
 
 With smart IDE like IntelliJ, it's an easy, but meaningful job.

**Comment by ZiyeHan** [comment]
I can do this job for you if you want. But there are many wikis and docs to update. Anyway, you make the decision, it's your call  :-)

**Comment by jenetics** [comment]
It depends on your personal workflow, and it is also a matter of taste, but I'm a big fan of Javadoc. This is  the reason why I put a lot of effort to have a decent Javadoc documentation. If I want to explore the API of a project, I usually open the Javadoc. If you do so for Jenetics, you can click on the `Selector` interface and you will get all known implementing classes.

Since your proposed change is an incompatible one and would also require a lot of changes in the existing documentations, I think it is not worth the effort.  Maybe can convince you using the Javadoc API for exploring the library classes. I think I did a great job on writing it ;-)
