### ISSUE TITLE
Population.empty() isn't empty

### ISSUE THREAD

**Issue by BFergerson** [jenetics/jenetics#234]
It's possible to modify Population.empty() like such:
```java
Genotype genotype = Genotype.of(
    IntStream.range(0, 10)
       .mapToObj(i -> DoubleChromosome.of(0, 10, 10))
       .collect(ISeq.toISeq())
);

Population pop = Population.empty();
pop.add(Phenotype.of(genotype, 1, chromosomes -> true));

System.out.println("Population size: " + pop.size());
System.out.println("Empty population size: " + Population.empty().size());
```

Outputs:
> Population size: 1
> Empty population size: 1

I was going to make a pull request and fix but I noticed you are trying to make Population immutable and the new version of Population doesn't have Population.empty(). Is there going to be a Population.empty() in the new immutable version of Population? And would you like me to make a pull request for fixing the current version of Population.empty()?

**Comment by jenetics** [comment]
It shouldn't be possible to add an element to an _empty_ Population. Instead an `UnsupportedOperationException` should be thrown, like in the Java `Collections.emptyList()` list. So this  is a bug and should be fixed. I will do this, since I already found the erroneous line. 

Yes, I'm working on an immutable Population class. This should make it easier to understand the code in the Engine class. I'm not yet sure whether I will remove the Population class completely and just use `ISeq<Phenotype>` as a replacement. The plan is to do this in version 4.0.

**Comment by jenetics** [comment]
Fix has been merged into r3.9.0 branch.
