### ISSUE TITLE
How to create fitness function that needs population information

### ISSUE THREAD

**Issue by darinyu** [jenetics/jenetics#286]
The following is an example of fitness function shown on frontpage of jenetics

```
    private static int eval(Genotype<BitGene> gt) {
        return gt.getChromosome()
                .as(BitChromosome.class)
                .bitCount();
    }
```

This is a fitness function that calculates individual fitness.

However, how do I write a fitness function of a chromosome where the fitness is based on
the average and standard deviation of the population?

Say chromosome only has one `DoubleGene, value=d` , and the fitness function returns 
should return `(d - avg_population) / standard_d_population`. How do I feed in information of the entire population?

**Comment by darinyu** [comment]
Actually, I think what I am asking is that, is there a way to intercept/process the result of population at end or beginning of each iteration?

**Comment by jenetics** [comment]
It is currently no standard way to use the current population in the fitness function. But what you can do is to define a _global_ `POP` value, where you store the current population which can then be accessed by your fitness function.

```java
public class OnesCounting {

    private static final AtomicReference<ISeq<Genotype<BitGene>>>
        POP = new AtomicReference<>();

    private static Integer count(final Genotype<BitGene> gt) {
        assert POP.get() != null;
        final ISeq<Genotype<BitGene>> pop = POP.get();

        //... Using the current population
        return ((BitChromosome)gt.getChromosome()).bitCount();
    }

    public static void main(String[] args) {
        final Engine<BitGene, Integer> engine = Engine
            .builder(
                OnesCounting::count,
                BitChromosome.of(20, 0.15))
            .populationSize(500)
            .selector(new RouletteWheelSelector<>())
            .alterers(
                new Mutator<>(0.55),
                new SinglePointCrossover<>(0.06))
            .build();

        final Phenotype<BitGene, Integer> best = engine.stream()
            .limit(100)
            // Set the current population.
            .peek(r -> POP.set(r.getGenotypes()))
            .collect(toBestPhenotype());

        System.out.println(best);
    }
}
```

**Comment by sachag678** [comment]
I am using a modified version of the code above and am running into an issue. The assertion that POP.get() != null is returning false, and ending the program. If I ignore the assertion, the POP is only getting updated after generation 0 at which point the fitness has been calculated for the initial Genetic Programs in the population. Is there a way to ensure that the POP gets updated before generation 0's fitness has been calculated so that this issue doesn't occur? 

    public class Test {

	static final ISeq<Op<Double>> Operations = ISeq.of(
			MathOp.SUB,
			MathOp.ADD,
			MathOp.MUL,
			MathOp.DIV);


	static final Var<Double> x1 = Var.of("x1", 0);
	static final Var<Double> x2 = Var.of("x2", 1);
	static final Var<Double> x3 = Var.of("x3", 2);
	static final Var<Double> x4 = Var.of("x4", 3);


	static final ISeq<Op<Double>> Terminals = ISeq.of(x1,x2,x3,x4);

	private static final AtomicReference<ISeq<Genotype<ProgramGene<Double>>>> POP = new AtomicReference<>();
	private static long generation;
	
	private static double error(final ProgramGene<Double> gt) {
		
		System.out.println(gt.toParenthesesString() + " : Current Generation - " + generation);

		assert POP.get() != null;
		final ISeq<Genotype<ProgramGene<Double>>> pop = POP.get();

		//... Using the current population
		if(pop == null) {
			System.out.println("Length of pop: "  + 0);
		}else {
			System.out.println("Length of pop: "  + pop.length());
		}

		return 1.0;
	}

	public static void main(String[] args) {

		final Codec<ProgramGene<Double>, ProgramGene<Double>> CODEC =
				Codec.of(
						Genotype.of(ProgramChromosome.of(
								2, ch->ch.getRoot().size()<=20,  Operations, Terminals)),
						Genotype::getGene
						);

		final Engine<ProgramGene<Double>, Double> engine = Engine
				.builder(Test::error, CODEC)
				.populationSize(3)
				.selector(new RouletteWheelSelector<>())
				.alterers(
						new Mutator<>(0.01),
						new SinglePointCrossover<>(0.2))
				.build();

		final ProgramGene<Double> best = engine.stream()
				.peek(r -> POP.set(r.getGenotypes()))
				.peek(r -> generation=r.getGeneration())
				.limit(2)
				// Set the current population.
				.collect(EvolutionResult.toBestGenotype())
				.getGene();
		
		System.out.println("-------------------------");
		System.out.println(best.toParenthesesString());
	    }
    }

**Comment by sachag678** [comment]
I've noticed it says that the peek will call a specific function on every finished generation (Listing 1.11 pg 29 of the Manual). So maybe there is no way to force it to begin before?

**Comment by jenetics** [comment]
If your fitness (error) function depends on the state of the whole population, you might consider using the [Engine.Evaluator](http://jenetics.io/javadoc/jenetics/io/jenetics/engine/Engine.Evaluator.html) interface. This gives you a greater flexibility for your fitness function. This concept has been generalized in for the upcoming version 5.0.

If you want a pre-evaluated generaton zero, you can do this manually, by creating your evolution stream with an initial population. If you evaluate the fitness before creating the stream, you can access the fitnesses of generation zero.

Since the `Engine.Evaluator` has been improved for version 5.0.0, I would recommend this solution,

**Comment by sachag678** [comment]
I figured out a way to do it by manually creating an initial population and storing it in the Atomic Reference before running EvolutionStream so that it can be used during evaluation of generation 0. Though I ultimately ended up going with your suggestion of using Engine.Evaluator. Thanks for the response!
