### ISSUE TITLE
Set fixed seed with RandomRegistry, but still random results each time?

### ISSUE THREAD

**Issue by Yuanyuan517** [jenetics/jenetics#438]
Hi, I meet same problem as written by ChristianThor. And I would like to get deterministic results
by setting seeded PRNG(to compare how time duration influence the result in GA), any clues?

Thank you!

_Originally posted by @Yuanyuan517 in https://github.com/jenetics/jenetics/issues/428#issuecomment-453541299_

**Comment by jenetics** [comment]
Does this comment solve your problem? 
https://github.com/jenetics/jenetics/issues/428#issuecomment-453619752

**Comment by jenetics** [comment]
You forgot one important part when defining the evolution `Engine`.
```java
final Engine<DoubleGene, Double> engine =
	Engine.builder(Function.identity(), CODEC)
		.executor(Runnable::run) // Important line
		.build();
```
The `Engine` must run in a single thread. With `.executor(Runnable::run)` a local and global random registry will work. With `.executor(Executors.newSingleThreadExecutor())` only the global random registry works. This is because the local random registry is working on the current thread and the executor `.executor(Runnable::run)` will execute all operations on the main thread.

**Comment by Yuanyuan517** [comment]
Thank you very much!

I didn't realize that even I didn't declare the executor, the threads are created by default.
Now I know the default value is set to ForkJoinPool.commonPool() and the number of running
threads depends on the CPU cores. 

With multiple threads created, although i set global random registry, the result is random
because one engine runs in multi threads and then the order of engine calls is not defined, right?

**Comment by jenetics** [comment]
:+1:  Exactly, that's the point.

**Comment by Yuanyuan517** [comment]
Thank you very much!
