### ISSUE TITLE
Constraining BitChromosome

### ISSUE THREAD

**Issue by ShivKJ** [jenetics/jenetics#544]
Hi,
I am trying to create bitchromosome(suppose it has size (or bit) 100) which has following constraints:
1) Atleast 12 bits must be chosen.
2) Atleast 7 bits from first 10 bits be chosen.

I was thinking of first selecting 7 out of first 10 bits and then selecting rest of the bits with (5/93) probability, possibly filtering the chromosome if number of selected bits turns out to be  less than 12.

It could be done by subclassing BitChromosome class then overring the newInstance method.

Is there a better way it can be done?

**Comment by jenetics** [comment]
These are very special constraints. But it's not only the `newInstance` method. The creation of an individual can be controlled by implementing a handcrafted `Factory<Genotpye<BitGene>>` instead of the normal `Genotpye` template. The second step would be to implement the `Constraint` interface, which is available since v5.0.0. This interface is used when an `Alterer` is _destroying_ your genotype.

**Comment by ShivKJ** [comment]
Ok,
Thanks
