### ISSUE TITLE
Specify maximize / minimize per objective in MOO

### ISSUE THREAD

**Issue by beatngu13** [jenetics/jenetics#546]
It is currently possible to specify `maximize()` or `minimize()` via the `Engine` builder, also the figures 4.1.9 and 4.1.10 from the user guide ([v5.0.0](http://jenetics.io/manual/manual-5.0.0.pdf)) show a Pareto front being maximized, respectively, minimized.

Is there a way to specify this per objective, in case one should be maximized and another one minimized? Or should this be handled in the fitness function, e.g., by maximizing/minimizing the corresponding negative?

PS: Do you prefer questions being asked here, on Stack Overflow, or somewhere else?

PPS: Thanks for this fantastic lib! 🙏

**Comment by jenetics** [comment]
Jenetics doesn't support mixed minimizing and maximizing in the current implementation. But I searched the current code base and found a way to overcome this limitation (untested, but it should work). What you have to do is to implement your own implementation of the `Vec` interface.
```java
public final class Vec3d implements Vec<double[]>, Serializable {
    private static final long serialVersionUID = 1L;

    private final double[] _data;

    public Vec3d(final double a, final double b, final double c) {
        _data = new double[]{a, b, c};
    }

    @Override
    public double[] data() {
        return _data;
    }

    @Override
    public int length() {
        return _data.length;
    }

    @Override
    public ElementComparator<double[]> comparator() {
        return (a, b, i) -> {
            switch (i) {
                // maximize this objective.
                case 0: return Double.compare(a[0], b[0]);
                // minimize this objective.
                case 1: return Double.compare(b[1], a[1]);
                // maximize this objective.
                case 2: return Double.compare(a[2], b[2]);
                default: throw new IllegalArgumentException();
            }
        };
    }

    @Override
    public ElementDistance<double[]> distance() {
        return (u, v, i) -> u[i] - v[i];
    }

    @Override
    public Comparator<double[]> dominance() {
        return (a, b) -> dominance(a, b, 3, comparator());
    }

    @Override
    public int hashCode() {
        return Arrays.hashCode(_data);
    }

    @Override
    public boolean equals(final Object obj) {
        return obj == this ||
            obj instanceof Vec3d &&
                Arrays.equals(((Vec3d)obj)._data, _data);
    }

    @Override
    public String toString() {
        return Arrays.toString(_data);
    }

    private static <T> int dominance(
        final T u,
        final T v,
        final int dimension,
        final ElementComparator<? super T> comparator
    ) {
        boolean udominated = false;
        boolean vdominated = false;

        for (int i = 0; i < dimension; ++i) {
            final int cmp = comparator.compare(u, v, i);

            if (cmp > 0) {
                udominated = true;
                if (vdominated) {
                    return 0;
                }
            } else if (cmp < 0) {
                vdominated = true;
                if (udominated) {
                    return 0;
                }
            }
        }

        if (udominated == vdominated) {
            return 0;
        } else if (udominated) {
            return 1;
        } else {
            return -1;
        }
    }
}
```
The example implements a 3D-Vector, where the second objective is minimized instead of maximized. You have to implement the `comparator` method with the desired behavior. The essential part is the private `dominance` method, where I calculate the Pareto dominance of two points. This method takes the element comparator, which we tweaked. As I said: untested, but it should do the trick.

Creating a Github ticket for questions is the safer way, although I have a trigger for StackOverflow questions. But this trigger depends on the tagging on the question.

**Comment by beatngu13** [comment]
Perfect, thx!
