### ISSUE TITLE
Constraints for ProgramChromosome

### ISSUE THREAD

**Issue by michiL96** [jenetics/jenetics#664]
Hi,
I'm pretty new with jenetics and I'm wondering how I can modify a ProgramChromosome in order to satisfy some constraints and repair the ProgramChromosome using the Constraints interface.

**Comment by jenetics** [comment]
Yes, creating a `Constraint` object for a `ProgramChromosome` needs a little bit of preparation. The following code shows what you need to do.

```java
final static Constraint<ProgramGene<Double>, Double> CONSTRAINT = Constraint.of(
    ProgramChromosomeTest::isValid,
    ProgramChromosomeTest::repair
);

private static boolean isValid(final Phenotype<ProgramGene<Double>, Double> pt) {
    final Tree<Op<Double>, ?> tree = pt.genotype().gene();
    // Do your validity checks with the given operation tree.
    return true;
}

private static Phenotype<ProgramGene<Double>, Double>
repair(final Phenotype<ProgramGene<Double>, Double> pt, final long generation) {
    final TreeNode<Op<Double>> tree = TreeNode
        .ofTree(pt.genotype().chromosome().gene());

    // The TreeNode is mutable, so you can repair/update it.
    repair(tree);

    final var flat = FlatTreeNode.of(tree);
    final var genes = flat.map(t -> gene(pt.genotype().gene(), t));
    final var chromosome = pt.genotype().chromosome().newInstance(genes);
    return Phenotype.of(Genotype.of(chromosome), generation);
}

private static void repair(final TreeNode<Op<Double>> tree) {
    // Repair your tree.
}

private static ProgramGene<Double> gene(
    final ProgramGene<Double> template,
    final FlatTree<Op<Double>, ?> tree
) {
    return template.newInstance(
        tree.value(),
        tree.childOffset(),
        tree.childCount()
    );
}
```
A constraint consists of two parts, the validator (`isValid(Tree)` method) and the repairer (`repair(Phenotype, long)` method). You check the validity usually on the `Tree` object, instead of the phenotype. The `isValid` method shows how to obtain the AST from the phenotype. For repairing the AST, you need a mutable version of the `Tree` interface. How to get it is shown in the `repair` method. After you have repaired the tree you need to create a phenotype again. You can also have a look at the [TreeMutator](https://github.com/jenetics/jenetics/blob/master/jenetics.ext/src/main/java/io/jenetics/ext/TreeMutator.java) class.

I hope this was helpful in implementing your needed constraint.

**Comment by michiL96** [comment]
Thank you very much, this is what I was looking for.
