### ISSUE TITLE
Custom Chromosome[question]

### ISSUE THREAD

**Issue by antoniogarmendia** [jenetics/jenetics#676]
Hi,

I started using Jenetics just a few days ago, and I find it very useful. Probably this question is a little bit silly, sorry for that.

I would like to implement an IntegerGene chromosome, but I would like to generate the chromosome in the sense that the genes are interrelated. That means that I would like to generate custom chromosomes. To do this, I implement Chromosome<IntegerGene> an Override the newInstance method. The thing is that is not working, because sometimes the best genotype that I get as a result, does not fulfil the interrelated constraints between the genes.

I implemented this example. 

[Sample-Chromosome.zip](https://github.com/jenetics/jenetics/files/4443225/Sample-Chromosome.zip)

Description of the classes:

SampleIntegerChromosome: The mapOfRelationships has an integer and a list of its dependencies. For example: if 11 -> [0,10] means that the 11's gene must be equal to gene 0 or 10 and after I generate a random chromosome I just try to update the new instance with the given dependencies.

SampleProblem -> Implementation of Problem interface

SampleCustomChromosome -> main

Would you please take a look at the code? Thanks in advance.

Kind regards,
Antonio

**Comment by jenetics** [comment]
Hi Antonio,

the problem is, that the used alterers (`MultiPointCrossover` and `UniformCrossover`) don't know anything about the special constraint of your integer chromosomes. Therefore, this alterers are ruthlessly destroying the chromosome constraint. There are three solutions for this problem:

1) Implement your own alterer, which obeys the constraints of your `SampleIntegerChromosome`. An example for this kind of alterers is the `PartiallyMatchedCrossover` class, which is part of the library. It is used for permutation problems, where it is not allowed to have duplicate genes.

2) Implement the `Chromosome.isValid` method and return `false` for invalid chromosomes. Jenetics will replace invalid chromosomes with newly created one. Currently, this method always return `true`.

3) Implement the `io.jenetics.engine.Constraint` interface and try to repair invalid chromosomes. You can define a `Constraint` in the `Engine.Builder`.

Depending on how difficult it is to repair invalid chromosomes, I would aim for solution 1) or 3).

Regards
Franz

**Comment by jenetics** [comment]
One additional problem in your code: the `Chromosome.newInstance(ISeq)` method **must** always return a new instance of the chromosome.

```java
@Override
public Chromosome<IntegerGene> newInstance(ISeq<IntegerGene> genes) {
    return new SampleIntegerChromosome(genes, mapOfRelationships, max);
}
```

Otherwise you will change existing chromosomes. Jenetics assumes that **all** gene and chromosome implementations are *immutable*. Having *mutable' genes and chromosomes will lead to faulty results.

**Comment by antoniogarmendia** [comment]
Hi Franz,

Thanks for your answer. You are absolutely right. I followed your advice and implemented the proposed solution number 3. It works as expected after the test of 30 generations.

[Sample-Chromosomev1.zip](https://github.com/jenetics/jenetics/files/4448911/Sample-Chromosomev1.zip)

Kind regards,
Antonio
