### ISSUE TITLE
MSeq to PermutationChromosome

### ISSUE THREAD

**Issue by antoniogarmendia** [jenetics/jenetics#709]
Hi,

I have been using the Constraint interface to repair permutation chromosomes. In this sense, I convert the permutation chromosomes to MSeq, perform some changes and convert it again to PermutationChromosome. It seems to me that the conversion `PermutationChromosome.of(MSeq.toISeq());` does not have the expected behaviour, because when I iterate over those elements the allele() cannot be cast to an Integer. 

Find attached the example. The SampleConstraint.java implements the Constraint interface and within it the validatePermutationChromosome that test each gene type.

[sample-factory-permutation-chromosome.zip](https://github.com/jenetics/jenetics/files/4690824/sample-factory-permutation-chromosome.zip)

Would you give it a try? I am using the version 6.0.0. Thanks in advance. 

Kind regards,
Antonio

**Comment by jenetics** [comment]
Hi,
Some comments to your code:

1) If you take the road of _raw_-types, you have to do it for everything. Generifying the `Constraint` gives you a false sens of security. It's very easy to get lost when casting (to the wrong) types.

2) Instead of
```java
private static final Genotype ENCODING = Genotype.of(
    (Chromosome)PermutationChromosome.of(
        IntStream.rangeClosed(1,5).boxed()
            .collect(ISeq.toISeq())
        ),
    (Chromosome)BitChromosome.of(25)
);	
```
you should write
```java
private static final Genotype ENCODING = Genotype.of(
    (Chromosome)PermutationChromosome.ofInteger(5),
    (Chromosome)BitChromosome.of(25)
);
```
3) The `PermutationChromosome.of(ISeq)` factory method is not meant to create _repaired_ chromosomes. The elements of the given `ISeq` just contains the valid alleles which are permuted by the chromosome. Which means, that the given alleles are shuffeld. This behavior is different to that of the `BitChromosome`. If you need an instance with an exact order, use the `PermutationChromosome(ISeq)` constructor. I think I have this documented in the Javadoc.

4) If you needs to _repair_ a `PermutationChromosome`, you probably have chosen the wrong encoding. The `PermutationChromosome` is meant to be used for combinatorial problems. Do you have to repair any invalid combinations?    

5)  The `AnyGene` are no placeholder for some unknown genes. Defining a constraint with `AnyGene` is wrong. You have chosen using mixed `Genotype`. There is no way back. You have to use _raw_-types here as well.

```java
public class SampleConstraint 
    implements Constraint<AnyGene<?>,Double> 

{
...
}
```
And then you try to cast an `AnyGene` to an `EnumGene`!?

6) As already mentioned, you lost yourself in tracking the right type.
```java
MSeq<EnumGene<IntegerGene>> repairPc = 
    MSeq.of((PermutationChromosome) individual.genotype().get(0));
```
`MSeq<EnumGene<IntegerGene>>` should be `MSeq<EnumGene<Integer>>`, right?

So using mixed `Genotype`s brought you on the dark side of the library (type system) ;-)

**Comment by antoniogarmendia** [comment]
Hi,

Thank you very much for all the comments. I will fix it right away. 

Regarding comment number 5, I cannot use Genotype
```
public class SampleConstraint 
    implements Constraint<Genotype,Double>
```
and it should be a class that inherits Gene. How should I do it? 

Kind regards,
Antonio

**Comment by jenetics** [comment]
Raw-Types all the way down.
```java
@SuppressWarnings({ "unchecked", "rawtypes" })
class C implements Constraint {
	@Override
	public boolean test(Phenotype individual) {
		return false;
	}
	@Override
	public Phenotype repair(Phenotype individual, long generation) {
		return null;
	}
}
```
