### ISSUE TITLE
Complex genome - how to

### ISSUE THREAD

**Issue by nkoding** [jenetics/jenetics#804]
Hi there,

I have a question but first of all: great work with jenetics :) i like the design a lot!

I am already stuck and I'm still in the design phase.

My objective is to solve a complex problem that requires not just different chromosomes as in MixedGenotype.java example.

I also need one chromosome to appear once or N times as in DynamicGenotype example.
That "repeating" chromosome should be a complex type of varying genes.

And if that is not enough yet, I want to use one or many BitGenes within a chromosome.

Maybe grammar based evolution could help me here? (mentioned in #767)

this is the structure of what I want to evolve:
     
     * bitChromosome (len: 1-20 bits)
     * intChromosome (len: 1-5 ints of range 1-100)
     * enumChromosome (A,B,C)
     
     * complexRepeatedChromosome {
     **  bitGene (len: 2-50 bits)
     **  intGene (range: 0-999)
     **  intGene (range: 1-1000)
     **  enumGene (D,E,F)

Two example phenotypes (each line represents a Chromosome):

**1)**
```
01010 
1,4,2
A 
1111111111111010010101 | 11 | 20 | D
101101000010101 | 40 | 510 | F
111101001010010101 | 80 | 901 | E
111010010101 | 28 | 32 | E
100000001010010101 | 18 | 54 | E
```

**2)**
```
000101010 
70,8,56,72,97
C
11111111111111110110010101 | 111 | 720 | D
10110110011101010101 | 840 | 910 | E
1111010011110111111111111111110010101 | 580 | 608 | D
```
     
Any help would be very appreciated :)

Best regards, 
nkoder

**Comment by jenetics** [comment]
Hi @nkoding,
I would suggest that you make yourself familiar with the `Codec` interface and it's capabilities. If you have a complex problem domain, it is not always possible to encode it _directly_ with the given genes/chromosome. So additional transformations are necessary. This is required due to the main _constraint_ of Jenetics, that you can't mix the gene types within a `Genotype` and a `Genotype` has a fixed number of chromosomes.

That said, I tried to created `Codec`s for the first three chromosomes of your example, which is then combined int the _final_ `codec`.

```java
enum Type { A, B, C }
record DomainObject(int[] bits, int[] ints, Type type){}

final Codec<int[], DoubleGene> c1 = Codec.of(
        Genotype.of(DoubleChromosome.of(DoubleRange.of(0.0, 1.0), IntRange.of(1, 21))),
        gt -> gt.chromosome().as(DoubleChromosome.class).toArray()
    )
    .map(v -> DoubleStream.of(v).mapToInt(d -> d < 0.5 ? 0 : 1).toArray());

final Codec<int[], DoubleGene> c2 = Codec.of(
        Genotype.of(DoubleChromosome.of(DoubleRange.of(0.0, 100.0), IntRange.of(1, 6))),
        gt -> gt.chromosome().as(DoubleChromosome.class).toArray()
    )
    .map(v -> DoubleStream.of(v).mapToInt(d -> (int)Math.round(d)).toArray());

final Codec<Type, DoubleGene> c3 = Codecs.ofVector(DoubleRange.of(0.0, 2.0))
    .map(v -> Type.values()[(int)Math.round(v[0])]);

// Combine the sub-codecs into the final "codec".
final Codec<DomainObject, DoubleGene> codec = Codec.of(
    ISeq.of(c1, c2, c3),
    v -> new DomainObject((int[])v[0], (int[])v[1], (Type)v[2])
);

final Function<DomainObject, Double> fitness = v -> 1.0;

final Engine<DoubleGene, Double> engine = Engine
    .builder(fitness, codec)
    .build();
``` 
The example should illustrate what is possible if you put some effort in the codec _mapping_ functions.
