### ISSUE TITLE
how to optimize jenetics on multi-core cpu

### ISSUE THREAD

**Issue by youngcle** [jenetics/jenetics#885]
i am using jenetics in my application for almost 5 years. It's an excellent lib for compensation optimize problem.

from last month, i start to profile my app use JProfiler,after remove some low performance "String parse" code,my app can envolve 50% more generation than before.

but when i looking at "thread view" as following:

![graph](https://github.com/jenetics/jenetics/assets/15942918/ae34e51c-299b-4b1f-9ab3-57907b48a440)

most cpu in this chart is yellow, which means "waiting",
very few part are green(means "runnable");

there are no red time,means "blocked" which have been removed. i beleive most low performance code like "string parse, Vector add" have been removed and the JProfiler shows nothing strange in hotspot chart.

i've read the "concurrency" part in manual, switch to fixedThreadPool and change batch size, the result is the same.

my workstation has 2 Xeon cpus(48 thread) and run with ubuntu 2204

the cpu utilization goes up to 4800% at the begining, and goes down to about 900% after 5 seconds , and last to the end.

my question is :
1 whether the reason of  low utilization is in my bussiness logic code or in jenetics?
2 how to fix that or optimize that？

thanks

**Comment by jenetics** [comment]
By default, the library executes the fitness function, and some parts of the selection algorithm, concurrently. The GA itself is executed in a serial way, one generation after another. Before the next generation can be executed, the previous one must first be finished. This the main _synchronization_ point of the library. If your fitness function isn't expensive, you might end with the CPU utilization you showed. The full CPU utilization at the beginning is due to the initial fitness calculations. After this phase, the fitness function is only calculated if needed, otherwise it is _cached_ in the phenotype.

One thing you can try is to increase the population size and look if you can find a usable solution faster. A bigger population means more calculations which can be parallelized.
